version: '3.8'

services:
  api:
    env_file:
      - .env.dev
    volumes:
      - ./certs/dev:/https
    ports:
      - '5000:8080'
      - '5001:8443'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:8443;http://+:8080
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${CERT_PASSWORD}
      ConnectionStrings__DefaultConnection: 'Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}'
  
  postgres:
    ports:
      - '5432:5432'